### ISSUE TITLE
Unexpected token '.'

### ISSUE THREAD

**Issue by Zaxerion** [LongAKolangle/discord-owo-selfbot#10]
file:///home/ubuntu/discord-owo-selfbot/lib/DataCollector.js:352
    guildid = await getResult(listGuild(cache?.guildID));
                                                                    ^

SyntaxError: Unexpected token '.'

![image](https://github.com/LongAKolangle/discord-owo-selfbot/assets/24669898/31d24f0e-53bc-4be7-a946-f328b0c8a55a)

**Comment by LongAKolangle** [comment]
> file:///home/ubuntu/discord-owo-selfbot/lib/DataCollector.js:352 guildid = await getResult(listGuild(cache?.guildID)); ^
> 
> SyntaxError: Unexpected token '.'
> 
> ![image](https://user-images.githubusercontent.com/24669898/245499214-31d24f0e-53bc-4be7-a946-f328b0c8a55a.png)

Node.js version must be at least v14.0.0
as normal, using apt install on linux only meet v12.x.x, use wget command to install
