### ISSUE TITLE
Error: Failed to find real token.

### ISSUE THREAD

**Issue by dkfjdlkfjdklfdlkfjdkljfkldjfldj** [LongAKolangle/discord-owo-selfbot#2]
```8:28:29 PM [INFO] Checking Account...
Error: Failed to find real token.
    at DiscordAuthWebsocket._findRealToken (E:\NonSystemFiles\bot\discord-owo-selfbot\node_modules\discord.js-selfbot-v13\src\util\RemoteAuth.js:427:66)
    at DiscordAuthWebsocket._findRealToken (E:\NonSystemFiles\bot\discord-owo-selfbot\node_modules\discord.js-selfbot-v13\src\util\RemoteAuth.js:472:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
8:28:47 PM [PROMISE.ERROR] Error: Failed to find real token.
```

HELP PLEASE HOW CAN I SOLVE THIS?
gives this error when i try to run the code 
![image](https://user-images.githubusercontent.com/86155970/235954284-67a48525-50a2-4cd3-9197-3f60ae30964d.png)

**Comment by dkfjdlkfjdklfdlkfjdkljfkldjfldj** [comment]
Any solution ?

**Comment by LongAKolangle** [comment]
> Any solution ?

No, as said. The only way is to wait for 5-7 days and you can continue using that account
Other accounts are not affected, so try using them if possible

**Comment by dkfjdlkfjdklfdlkfjdkljfkldjfldj** [comment]
ugh sure thanks!

**Comment by dkfjdlkfjdklfdlkfjdkljfkldjfldj** [comment]
I have a question
Can I still try to login in the account in which i have problem or i should completely ignore the account that's rate limited for 7days?

**Comment by LongAKolangle** [comment]
> I have a question Can I still try to login in the account in which i have problem or i should completely ignore the account that's rate limited for 7days?

should ignore it, in order to prevent ip-rate-limiting

**Comment by dkfjdlkfjdklfdlkfjdkljfkldjfldj** [comment]
ah thanks

**Comment by Colly001** [comment]
You should make a way when you get the human verification , to be able to complete it manually at least

**Comment by LongAKolangle** [comment]
> You should make a way when you get the human verification , to be able to complete it manually at least

What do you mean?
