### ISSUE TITLE
Account check-in falied

### ISSUE THREAD

**Issue by crazyeee** [LongAKolangle/discord-owo-selfbot#32]
![Screenshot (32)](https://github.com/LongAKolangle/discord-owo-selfbot/assets/157721021/0b10f18e-ff2c-4fc6-bf76-bf1255243124)
i tried to login as usual but did not work

**Comment by LongAKolangle** [comment]
Have a look at this one: https://github.com/LongAKolangle/discord-owo-selfbot/discussions/15#discussioncomment-6834369
