### ISSUE TITLE
Huntbot Send Problem

### ISSUE THREAD

**Issue by Kayows12** [LongAKolangle/discord-owo-selfbot#35]
nvm it works

**Comment by TSWarrior** [comment]
may i know how it worked
mine isnt working it by defaults owo ht 24h whuch owo doesnt understands

**Comment by Kayows12** [comment]
> may i know how it worked mine isnt working it by defaults owo ht 24h whuch owo doesnt understands

I don't know but may be you need to upgrade your duration to more than 3 h
