### ISSUE TITLE
???

### ISSUE THREAD

**Issue by rudii-v** [LongAKolangle/discord-owo-selfbot#9]
![SmartSelect_20230604-184335_ ](https://github.com/LongAKolangle/discord-owo-selfbot/assets/87123741/c94d351a-d97e-45fa-8b2f-8f53ba3dafc5)
Am I the one who entered the wrong token? Or bugs?

**Comment by LongAKolangle** [comment]
which login method are you using?

**Comment by rudii-v** [comment]
With token, and with Password. But both are the same.

**Comment by rudii-v** [comment]
Why is it @LongAKolangle

**Comment by rudii-v** [comment]
![Screenshot_20230604-202801_ ](https://github.com/LongAKolangle/discord-owo-selfbot/assets/87123741/4ce130c6-88a5-40b6-9666-183e3b6b0a44)
💀💀

**Comment by Draconian360** [comment]
Your token shows...

**Comment by rudii-v** [comment]
Thanks for telling

**Comment by rudii-v** [comment]
![Screenshot_20230604-202801_ ](https://github.com/LongAKolangle/discord-owo-selfbot/assets/87123741/ea794515-9301-4439-ba48-4695d438b732)
💀💀

**Comment by LongAKolangle** [comment]
> ![Screenshot_20230604-202801_ ](https://user-images.githubusercontent.com/87123741/243181605-ea794515-9301-4439-ba48-4695d438b732.jpg) 💀💀

This because of poor network
About the login, 
- With token: it may has been expired
- With password: the MFA Code must be Back-up Code or Google Authenticator

**Comment by rudii-v** [comment]
The token and password are correct

**Comment by rudii-v** [comment]
It's back, thanks for the answer
